name: Network Science
author: Tiejian Luo
email: tjluo@ucas.ac.cn
description: Actually, less is more!
github: https://github.com/tjluo-ucas/ns
resume_site: http://people.ucas.ac.cn/~tjluo
baseurl: "/ns"
permalink: /:year/:month/:day/:title/

